// <auto-generated />
using System;
using BuckeyeMarketplace.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuckeyeMarketplace.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BuckeyeMarketplace.API.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BuckeyeMarketplace.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BuckeyeMarketplace.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Outfits",
                            Description = "Hand-dyed OSU scarlet and gray crewneck sweatshirt. Made-to-order, one of a kind. Unisex sizing, runs slightly oversized. Machine wash cold.",
                            ImageUrl = "/images/Sweatshirt.png",
                            PostedDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 38.00m,
                            SellerName = "AlexDesigns",
                            Title = "Hand-Dyed Scarlet Tie-Dye Crewneck"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Outfits",
                            Description = "Thrifted denim jacket with hand-painted OSU Block O on the back using fabric paint. Size M. Truly one of a kind.",
                            ImageUrl = "/images/Jacket.png",
                            PostedDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 55.00m,
                            SellerName = "AlexDesigns",
                            Title = "Upcycled Denim Jacket - Block O Back"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Accessories",
                            Description = "Hand-crocheted bucket hat in OSU scarlet. Stretchy and fits most head sizes. Perfect for game days or everyday wear.",
                            ImageUrl = "/images/Hat.png",
                            PostedDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 22.00m,
                            SellerName = "YarnByJess",
                            Title = "Crocheted Scarlet Bucket Hat"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tanks",
                            Description = "Original design screen-printed on a Bella Canvas tank. Unisex sizing S-XL. Soft, lightweight fabric.",
                            ImageUrl = "/images/Tank.png",
                            PostedDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 18.00m,
                            SellerName = "AlexDesigns",
                            Title = "Custom Graphic Tank - Made in Columbus"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Stickers",
                            Description = "Set of 10 original hand-drawn vinyl stickers. Waterproof and laptop-safe.",
                            ImageUrl = "/images/Stickers.png",
                            PostedDate = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 8.00m,
                            SellerName = "DoodlesByKayla",
                            Title = "OSU Campus Sticker Pack (10 Stickers)"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Blankets",
                            Description = "Arm-knitted chunky blanket in cream and gray. Super cozy for dorm nights or studying. Approx 40 x 50 inches.",
                            ImageUrl = "/images/blanket.jpeg",
                            PostedDate = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 65.00m,
                            SellerName = "KnottyByNature",
                            Title = "Chunky Arm-Knit Throw Blanket"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Skirts",
                            Description = "Hand-sewn pleated mini skirt in heather gray. Elastic waistband, size S/M.",
                            ImageUrl = "/images/Skirt.png",
                            PostedDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 28.00m,
                            SellerName = "MadisonCrafts",
                            Title = "Pleated Mini Skirt - OSU Gray"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Accessories",
                            Description = "Set of 3 handmade resin bookmarks with real pressed flowers. Glossy finish, gold ribbon tassel.",
                            ImageUrl = "/images/Bookmark.png",
                            PostedDate = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 12.00m,
                            SellerName = "BloomByBri",
                            Title = "Pressed Flower Resin Bookmark Set"
                        });
                });

            modelBuilder.Entity("BuckeyeMarketplace.API.Models.CartItem", b =>
                {
                    b.HasOne("BuckeyeMarketplace.API.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckeyeMarketplace.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BuckeyeMarketplace.API.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
